title: Adam Hamden 
logo: /assets/img/Hamden_Adam_pic.png
description: Personal website with a few of my projects over the years
show_downloads: false
google_analytics: G-YD6YHHXQRH
theme: jekyll-theme-minimal
